name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Use Node.js
      uses: actions/setup-node@v404

    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npx playwright install --with-deps
    - run: npm run test:e2e
